#!/usr/bin/env bash
# Refresh a markdown snapshot of HitM calendar (khal) + tasks (todoman) for
# local agents and sprint planning. Safe to run before standups or plan updates.
#
# Environment:
#   FM_BASE_DIR        — repo root (default: parent of this script's directory)
#   SCHEDULE_DAYS      — how many days forward to list from today (default: 90)
#   SCHEDULE_SNAPSHOT  — output file (default: governance/HITM_SCHEDULE_SNAPSHOT.md)
#   KHAL_CAL           — optional: pass through to khal -a (include only this calendar)
#
# Requires: khal, todo (todoman), python3 (for portable date math)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASE_DIR="${FM_BASE_DIR:-$(cd "$SCRIPT_DIR/../.." && pwd)}"
DAYS="${SCHEDULE_DAYS:-90}"
OUT="${SCHEDULE_SNAPSHOT:-$BASE_DIR/governance/HITM_SCHEDULE_SNAPSHOT.md}"

require_cmd() {
  if ! command -v "$1" &>/dev/null; then
    printf 'Error: required command %q not in PATH.\n' "$1" >&2
    exit 1
  fi
}

require_cmd khal
require_cmd todo
require_cmd python3

START="$(python3 -c "from datetime import date; print(date.today().isoformat())")"
END="$(python3 -c "from datetime import date, timedelta; d=int(${DAYS}); print((date.today()+timedelta(days=d)).isoformat())")"

KHAL_EXTRA=()
if [[ -n "${KHAL_CAL:-}" ]]; then
  KHAL_EXTRA=(-a "$KHAL_CAL")
fi

mkdir -p "$(dirname "$OUT")"
TMP="${OUT}.tmp.$$"
trap 'rm -f "$TMP"' EXIT

GEN_ISO="$(python3 -c "from datetime import datetime, timezone; print(datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ'))")"

{
  printf '%s\n' "<!-- Generated by scripts/schedule_agent_sync.sh — do not edit by hand. -->"
  printf '%s\n' ""
  printf '%s\n' "# HitM schedule and task snapshot"
  printf '%s\n' ""
  printf '%s\n' "**Generated (UTC):** ${GEN_ISO}"
  printf '%s\n' "**Window:** ${START} through ${END} (inclusive range passed to \`khal list\`)"
  printf '%s\n' ""
  printf '%s\n' "## Where this data lives on disk"
  printf '%s\n' ""
  printf '%s\n' "| Store | Path | Tool |"
  printf '%s\n' "| --- | --- | --- |"
  printf '%s\n' "| Calendar events (ICS, vdir) | \`~/.local/share/calendars/work/\` | khal (\`~/.config/khal/config\`) |"
  printf '%s\n' "| Tasks / VTODO (ICS, vdir) | \`~/.local/share/calendars/tasks/\` (glob in todoman config) | todoman (\`~/.config/todoman/config.py\`) |"
  printf '%s\n' ""
  printf '%s\n' "Todoman stores **tasks** as separate \`.ics\` VTODO files; khal stores **events**. Many desktop clients sync both via CalDAV/vdirsyncer; agents read this **snapshot** in-repo after you run the script."
  printf '%s\n' ""
  printf '%s\n' "## Calendar (\`khal list\`)"
  printf '%s\n' ""
  printf '%s\n' '```'
  khal list "${KHAL_EXTRA[@]}" "$START" "$END" 2>&1 || true
  printf '%s\n' '```'
  printf '%s\n' ""
  printf '%s\n' "## Tasks (\`todo list\` — all lists)"
  printf '%s\n' ""
  printf '%s\n' '```'
  todo --color never list 2>&1 || printf '(todo list failed — check todoman config)\n'
  printf '%s\n' '```'
  printf '%s\n' ""
  printf '%s\n' "## Sprint / absence hints for agents"
  printf '%s\n' ""
  printf '%s\n' "- Treat **all-day** lines and **recurring** markers (\`⟳\`) in the calendar block as **time windows** or standing commitments."
  printf '%s\n' "- Cross-check **strategic phase/stage** dates in \`strategy/strategic-roadmap-reframe-53be/\` with this snapshot when planning execution density."
  printf '%s\n' "- Tasks with **due dates** in todoman appear in list output; use \`todo new \"Summary\" -d YYYY-MM-DD\` to add dated work items agents should respect."
  printf '%s\n' ""
} >"$TMP"

mv "$TMP" "$OUT"
trap - EXIT
printf 'Wrote %s\n' "$OUT"
