#!/usr/bin/env bash
# schedule_skill_gap.sh — weekly Cursor skill-gap evidence gather + report stub.
#
# Mirrors Claude's scheduled skill-gap routine locally: runs transcript_pattern_scan
# and writes a dated report under strategy/automations/reports/ for HitM review.
# Does not auto-build skills — wishlist-only per skill-gap-detection doctrine.
#
# Usage:
#   ./scripts/local/schedule_skill_gap.sh
#   ./scripts/local/schedule_skill_gap.sh --days 14
#   ./scripts/local/schedule_skill_gap.sh --print-cron
#
# Cron install: run --print-cron, paste into crontab -e (same pattern as setup_backup_cron.sh).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASE_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
DAYS=14
PRINT_CRON=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --days) DAYS="$2"; shift 2 ;;
    --print-cron) PRINT_CRON=1; shift ;;
    -h|--help)
      sed -n '2,14p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *) printf 'Unknown option: %s\n' "$1" >&2; exit 1 ;;
  esac
done

if [[ "$PRINT_CRON" -eq 1 ]]; then
  printf '\n# Weekly Cursor skill-gap scan (Sunday 23:30 Asia/Manila = 15:30 UTC)\n'
  printf '30 15 * * 0 %s/scripts/local/schedule_skill_gap.sh >> /tmp/skill_gap_scan.log 2>&1\n\n' "$BASE_DIR"
  printf '# Optional: invoke on-demand skill review in an open Cursor session:\n'
  printf '# cursor agent --print --workspace %s --trust "/skill-gap-detection"\n\n' "$BASE_DIR"
  exit 0
fi

SCAN_SCRIPT="$BASE_DIR/scripts/dev/transcript_pattern_scan.sh"
REPORT_DIR="$BASE_DIR/strategy/automations/reports"
DATE_TAG="$(date -u +%Y-%m-%d)"
OUT="$REPORT_DIR/skill_gap_scan_${DATE_TAG}.md"

mkdir -p "$REPORT_DIR"

if [[ ! -x "$SCAN_SCRIPT" ]]; then
  printf 'Error: %s not found — merge transcript_pattern_scan script first.\n' "$SCAN_SCRIPT" >&2
  exit 1
fi

TMP_SCAN="$(mktemp)"
trap 'rm -f "$TMP_SCAN"' EXIT

"$SCAN_SCRIPT" --days "$DAYS" >"$TMP_SCAN"

{
  printf '%s\n' "# Cursor skill-gap scan — ${DATE_TAG}"
  printf '%s\n' ""
  printf '%s\n' "**Generated by:** \`scripts/local/schedule_skill_gap.sh\`"
  printf '%s\n' "**Agent lane:** Cursor (local cron / on-demand)"
  printf '%s\n' ""
  printf '%s\n' "> Wishlist only — review pattern table below; do not auto-build skills."
  printf '%s\n' ""
  cat "$TMP_SCAN"
  printf '%s\n' ""
  printf '%s\n' "## Next step"
  printf '%s\n' ""
  printf '%s\n' "HitM reviews hits; open a meeting TP or dispatch doc for approved builds."
} >"$OUT"

printf 'Wrote %s\n' "$OUT"
